/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    patients: Patient;
    appointments: Appointment;
    visits: Visit;
    invoices: Invoice;
    auditLogs: AuditLog;
    bookingRequests: BookingRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    patients: PatientsSelect<false> | PatientsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    bookingRequests: BookingRequestsSelect<false> | BookingRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Se genera a partir del nombre; para URLs públicas en el futuro.
   */
  slug?: string | null;
  phone: string;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  taxId?: string | null;
  practiceType: 'individual' | 'clinic';
  status: 'pending' | 'active' | 'suspended';
  /**
   * Nivel de suscripción; límites definidos en código (src/lib/plans.ts).
   */
  plan: 'free' | 'pro' | 'clinic' | 'plus' | 'public';
  upgradeRequest?: {
    requestedPlan?: ('free' | 'pro' | 'clinic' | 'plus' | 'public') | null;
    requestedAt?: string | null;
    note?: string | null;
  };
  /**
   * Cómo se creó este consultorio (analítica).
   */
  onboardingSource: 'self-serve' | 'manual';
  settings: {
    appointmentDurationMins: number;
    openTime: string;
    closeTime: string;
    /**
     * Todos los montos se muestran en esta moneda.
     */
    currency: 'DOP' | 'USD' | 'EUR' | 'MXN' | 'COP' | 'PEN' | 'CLP' | 'GTQ' | 'CRC' | 'PAB';
    /**
     * Todas las horas se muestran en esta zona horaria.
     */
    timezone:
      | 'America/Santo_Domingo'
      | 'America/Puerto_Rico'
      | 'America/New_York'
      | 'America/Mexico_City'
      | 'America/Bogota'
      | 'America/Lima'
      | 'America/Santiago'
      | 'America/Guatemala'
      | 'America/Costa_Rica'
      | 'America/Panama'
      | 'Europe/Madrid';
    /**
     * Nutrición agrega antropometría, laboratorio y la hoja de seguimiento.
     */
    consultTemplate?: ('general' | 'nutrition') | null;
    /**
     * Los pacientes agendan desde el enlace público, dentro del horario de cada médico.
     */
    onlineBookingEnabled?: boolean | null;
    /**
     * Permite pedir una cita fuera de los horarios publicados; el consultorio la revisa.
     */
    onlineRequestsEnabled?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'superAdmin' | 'owner' | 'doctor' | 'receptionist';
  /**
   * Obligatorio para todos los roles excepto superadministrador.
   */
  tenant?: (string | null) | Tenant;
  phone?: string | null;
  active?: boolean | null;
  emailVerified?: boolean | null;
  verifyTokenHash?: string | null;
  verifyTokenExp?: string | null;
  practitioner?: boolean | null;
  specialty?: string | null;
  licenseNumber?: string | null;
  /**
   * En la moneda del consultorio. Se usa al facturar.
   */
  consultationFee?: number | null;
  availabilityType?: ('regular' | 'onCall' | 'byAppointment') | null;
  availableDays?: ('sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat')[] | null;
  availableFrom?: string | null;
  availableTo?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients".
 */
export interface Patient {
  id: string;
  tenant: string | Tenant;
  /**
   * Se asigna automáticamente por consultorio.
   */
  mrn?: string | null;
  name: string;
  documentType?: ('cedula' | 'passport' | 'other') | null;
  documentNumber?: string | null;
  phone: string;
  email?: string | null;
  gender: 'male' | 'female' | 'other';
  dateOfBirth?: string | null;
  ageYears?: number | null;
  bloodGroup?: ('A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-') | null;
  address?: string | null;
  occupation?: string | null;
  nationality?: string | null;
  maritalStatus?: ('single' | 'married' | 'common-law' | 'divorced' | 'widowed') | null;
  religion?: string | null;
  referredBy?: string | null;
  insurance?: {
    provider?: string | null;
    affiliateNumber?: string | null;
    plan?: string | null;
  };
  emergencyContact?: {
    name?: string | null;
    relationship?: string | null;
    phone?: string | null;
  };
  /**
   * Se muestra de forma destacada en el expediente (seguridad).
   */
  allergies?: string | null;
  history?: {
    personal?: string | null;
    chronicConditions?: string | null;
    surgical?: string | null;
    family?: string | null;
    medications?: string | null;
    habits?: string | null;
    gynecoObstetric?: string | null;
    vaccines?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  tenant: string | Tenant;
  patient: string | Patient;
  doctor: string | User;
  start: string;
  durationMins: number;
  end?: string | null;
  reason?: string | null;
  status: 'scheduled' | 'checked-in' | 'completed' | 'cancelled' | 'no-show';
  isWalkIn?: boolean | null;
  source?: ('staff' | 'online') | null;
  /**
   * Se asigna automáticamente por día a pacientes sin cita.
   */
  tokenNumber?: string | null;
  cancellationReason?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: string;
  tenant: string | Tenant;
  appointment: string | Appointment;
  patient: string | Patient;
  doctor: string | User;
  visitDate: string;
  chiefComplaint?: string | null;
  symptoms?: string | null;
  physicalExam?: string | null;
  diagnosis?: string | null;
  /**
   * Se imprime en la receta como indicaciones generales.
   */
  treatmentPlan?: string | null;
  /**
   * Laboratorios, imágenes u otros estudios. Se imprime en la receta.
   */
  labOrders?: string | null;
  /**
   * Solo visibles para el personal clínico.
   */
  notes?: string | null;
  vitals?: {
    bpSystolic?: number | null;
    bpDiastolic?: number | null;
    pulse?: number | null;
    respiratoryRate?: number | null;
    temperatureC?: number | null;
    oxygenSaturation?: number | null;
    weightKg?: number | null;
    heightCm?: number | null;
    glucoseMgDl?: number | null;
  };
  nutrition?: {
    constipation?: ('yes' | 'no') | null;
    waterIntake?: ('good' | 'poor') | null;
    anxiety?: ('yes' | 'no') | null;
    stress?: ('yes' | 'no') | null;
    sleepHours?: number | null;
    sleepQuality?: string | null;
    goal?: string | null;
    usualWeightKg?: number | null;
    armCm?: number | null;
    waistCm?: number | null;
    abdomenCm?: number | null;
    glutesCm?: number | null;
    hipCm?: number | null;
    labHemogram?: string | null;
    labFastingGlucose?: number | null;
    labHba1c?: number | null;
    labGlucoseOther?: string | null;
    labTotalCholesterol?: number | null;
    labLdl?: number | null;
    labHdl?: number | null;
    labTriglycerides?: number | null;
    labUrinalysis?: string | null;
    labAbdominalUltrasound?: string | null;
    labThyroidUltrasound?: string | null;
    labStool?: string | null;
    changes?: string | null;
    exercise?: string | null;
    diet?: string | null;
  };
  prescription?:
    | {
        medicine: string;
        dosage?: string | null;
        frequency?: ('od' | 'bd' | 'tds' | 'qid' | 'sos' | 'other') | null;
        frequencyNote?: string | null;
        durationDays?: number | null;
        quantity?: string | null;
        instructions?: string | null;
        id?: string | null;
      }[]
    | null;
  followUpDate?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  tenant: string | Tenant;
  /**
   * Asignado automáticamente por consultorio (FAC-0001).
   */
  invoiceNumber?: string | null;
  visit?: (string | null) | Visit;
  patient: string | Patient;
  /**
   * Tomada de la configuración del consultorio al crear la factura.
   */
  currency?: string | null;
  lineItems: {
    description: string;
    quantity: number;
    unitAmount: number;
    /**
     * Cantidad × precio unitario.
     */
    amount?: number | null;
    id?: string | null;
  }[];
  totalAmount?: number | null;
  payments?:
    | {
        amount: number;
        method: 'cash' | 'card' | 'bank-transfer' | 'insurance' | 'other';
        receivedAt?: string | null;
        receivedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  amountPaid?: number | null;
  balanceDue?: number | null;
  paymentStatus?: ('unpaid' | 'partial' | 'paid') | null;
  voided?: boolean | null;
  voidReason?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: string;
  tenant: string | Tenant;
  user: string | User;
  action:
    | 'appointment.created'
    | 'appointment.cancelled'
    | 'appointment.status-changed'
    | 'invoice.voided'
    | 'payment.recorded'
    | 'user.created'
    | 'user.deactivated'
    | 'user.role-changed'
    | 'settings.updated'
    | 'tenant.suspended'
    | 'tenant.reactivated'
    | 'plan.upgrade-requested'
    | 'plan.upgrade-rejected'
    | 'plan.changed'
    | 'export.generated'
    | 'patient.created'
    | 'patient.updated'
    | 'visit.created'
    | 'visit.updated';
  targetCollection: string;
  targetId: string;
  /**
   * Texto legible, p. ej., "Canceló la cita de Ana Pérez de las 5:30 p. m.".
   */
  summary: string;
  /**
   * Contexto estructurado breve (rol anterior/nuevo, monto…). Nunca una copia completa del documento.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookingRequests".
 */
export interface BookingRequest {
  id: string;
  tenant: string | Tenant;
  patient: string | Patient;
  doctor?: (string | null) | User;
  preferredDate?: string | null;
  reason: string;
  urgent?: boolean | null;
  status: 'pending' | 'handled' | 'dismissed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'patients';
        value: string | Patient;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'visits';
        value: string | Visit;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'bookingRequests';
        value: string | BookingRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  phone?: T;
  address?: T;
  city?: T;
  country?: T;
  taxId?: T;
  practiceType?: T;
  status?: T;
  plan?: T;
  upgradeRequest?:
    | T
    | {
        requestedPlan?: T;
        requestedAt?: T;
        note?: T;
      };
  onboardingSource?: T;
  settings?:
    | T
    | {
        appointmentDurationMins?: T;
        openTime?: T;
        closeTime?: T;
        currency?: T;
        timezone?: T;
        consultTemplate?: T;
        onlineBookingEnabled?: T;
        onlineRequestsEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenant?: T;
  phone?: T;
  active?: T;
  emailVerified?: T;
  verifyTokenHash?: T;
  verifyTokenExp?: T;
  practitioner?: T;
  specialty?: T;
  licenseNumber?: T;
  consultationFee?: T;
  availabilityType?: T;
  availableDays?: T;
  availableFrom?: T;
  availableTo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients_select".
 */
export interface PatientsSelect<T extends boolean = true> {
  tenant?: T;
  mrn?: T;
  name?: T;
  documentType?: T;
  documentNumber?: T;
  phone?: T;
  email?: T;
  gender?: T;
  dateOfBirth?: T;
  ageYears?: T;
  bloodGroup?: T;
  address?: T;
  occupation?: T;
  nationality?: T;
  maritalStatus?: T;
  religion?: T;
  referredBy?: T;
  insurance?:
    | T
    | {
        provider?: T;
        affiliateNumber?: T;
        plan?: T;
      };
  emergencyContact?:
    | T
    | {
        name?: T;
        relationship?: T;
        phone?: T;
      };
  allergies?: T;
  history?:
    | T
    | {
        personal?: T;
        chronicConditions?: T;
        surgical?: T;
        family?: T;
        medications?: T;
        habits?: T;
        gynecoObstetric?: T;
        vaccines?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  tenant?: T;
  patient?: T;
  doctor?: T;
  start?: T;
  durationMins?: T;
  end?: T;
  reason?: T;
  status?: T;
  isWalkIn?: T;
  source?: T;
  tokenNumber?: T;
  cancellationReason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  tenant?: T;
  appointment?: T;
  patient?: T;
  doctor?: T;
  visitDate?: T;
  chiefComplaint?: T;
  symptoms?: T;
  physicalExam?: T;
  diagnosis?: T;
  treatmentPlan?: T;
  labOrders?: T;
  notes?: T;
  vitals?:
    | T
    | {
        bpSystolic?: T;
        bpDiastolic?: T;
        pulse?: T;
        respiratoryRate?: T;
        temperatureC?: T;
        oxygenSaturation?: T;
        weightKg?: T;
        heightCm?: T;
        glucoseMgDl?: T;
      };
  nutrition?:
    | T
    | {
        constipation?: T;
        waterIntake?: T;
        anxiety?: T;
        stress?: T;
        sleepHours?: T;
        sleepQuality?: T;
        goal?: T;
        usualWeightKg?: T;
        armCm?: T;
        waistCm?: T;
        abdomenCm?: T;
        glutesCm?: T;
        hipCm?: T;
        labHemogram?: T;
        labFastingGlucose?: T;
        labHba1c?: T;
        labGlucoseOther?: T;
        labTotalCholesterol?: T;
        labLdl?: T;
        labHdl?: T;
        labTriglycerides?: T;
        labUrinalysis?: T;
        labAbdominalUltrasound?: T;
        labThyroidUltrasound?: T;
        labStool?: T;
        changes?: T;
        exercise?: T;
        diet?: T;
      };
  prescription?:
    | T
    | {
        medicine?: T;
        dosage?: T;
        frequency?: T;
        frequencyNote?: T;
        durationDays?: T;
        quantity?: T;
        instructions?: T;
        id?: T;
      };
  followUpDate?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceNumber?: T;
  visit?: T;
  patient?: T;
  currency?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitAmount?: T;
        amount?: T;
        id?: T;
      };
  totalAmount?: T;
  payments?:
    | T
    | {
        amount?: T;
        method?: T;
        receivedAt?: T;
        receivedBy?: T;
        id?: T;
      };
  amountPaid?: T;
  balanceDue?: T;
  paymentStatus?: T;
  voided?: T;
  voidReason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookingRequests_select".
 */
export interface BookingRequestsSelect<T extends boolean = true> {
  tenant?: T;
  patient?: T;
  doctor?: T;
  preferredDate?: T;
  reason?: T;
  urgent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}